version: '3.1'

services:

    app:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        container_name: backend-core
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ../:/var/www
        networks:
            - laravel
            - database_default # existing database network

    nginx:
        image: nginx:alpine
        container_name: backend-core-nginx
        restart: unless-stopped
        ports:
            - "9000:80"
        volumes:
            - ../:/var/www
            - ./nginx:/etc/nginx/conf.d/
        networks:
            - laravel
        depends_on:
            - app

networks:
    laravel:
        driver: bridge
    database_default: # existing database network
        external: true
