version: '3'
services:
    app:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ../:/var/www
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - "9000:80"
        volumes:
            - ../:/var/www
            - ./nginx:/etc/nginx/conf.d/
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: laravel-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: thien
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - ../db_data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
        driver: local